### ISSUE TITLE
Stopwatch Meter questions

### ISSUE THREAD

**Issue by JVasselli** [naist-nlp/knn-seq#6]
https://github.com/naist-nlp/knn-seq/blob/45efbb4b72cb77e9de8b3b0f130125e09a42f74c/knn_seq/utils.py#L172

This class has very little documentation and I have some question.

As there's no typing, I don't know if we want to make sure n is always a number.  The way it's written n could be a Tensor, but it would break .avg

What is the expected behaviour for multiple calls to stop without calls to start.  For example:
start
wait 5 seconds
stop
wait 5 seconds
stop

I would expect the sum to be 5 seconds, but in the current implementation it is 15 seconds.

**Comment by de9uch1** [comment]
Solved in #109
